// linux_analysis_sql.h
// SQL statements for Linux forensic analysis database - Main declarations

#pragma once
#ifndef LINUX_ANALYSIS_SQL_H
#define LINUX_ANALYSIS_SQL_H

// Include modular SQL components
#include "DatabaseManager/SQL/linux_analysis_sql_tables.h"
#include "DatabaseManager/SQL/linux_analysis_sql_crud.h"
#include "DatabaseManager/SQL/linux_analysis_sql_llm.h"

namespace LinuxAnalysisSQL {

// Re-export all symbols for backward compatibility
using linux_analysis_sql_tables::CREATE_ALL_TABLES;
using linux_analysis_sql_tables::CREATE_LINUX_ANALYSIS_PROGRESS_TABLE;

using linux_analysis_sql_crud::INSERT_LOG_ENTRY;
using linux_analysis_sql_crud::INSERT_USER_INFO;
using linux_analysis_sql_crud::INSERT_GROUP_INFO;
using linux_analysis_sql_crud::INSERT_LOGIN_RECORD;
using linux_analysis_sql_crud::INSERT_SHELL_HISTORY;
using linux_analysis_sql_crud::INSERT_CRON_JOB;
using linux_analysis_sql_crud::INSERT_SSH_KEY;
using linux_analysis_sql_crud::INSERT_SSH_KNOWN_HOST;
using linux_analysis_sql_crud::INSERT_PACKAGE_INFO;
using linux_analysis_sql_crud::INSERT_NETWORK_CONNECTION;
using linux_analysis_sql_crud::INSERT_SYSTEMD_SERVICE;
using linux_analysis_sql_crud::INSERT_KERNEL_MODULE;
using linux_analysis_sql_crud::INSERT_FIREWALL_RULE;
using linux_analysis_sql_crud::INSERT_AUDIT_LOG;
using linux_analysis_sql_crud::INSERT_BROWSER_PROFILE;

// Container INSERT statements
using linux_analysis_sql_crud::INSERT_DOCKER_CONTAINER;
using linux_analysis_sql_crud::INSERT_DOCKER_IMAGE;
using linux_analysis_sql_crud::INSERT_DOCKER_VOLUME;
using linux_analysis_sql_crud::INSERT_PODMAN_CONTAINER;
using linux_analysis_sql_crud::INSERT_PODMAN_POD;

// Web server INSERT statements
using linux_analysis_sql_crud::INSERT_APACHE_ACCESS_LOG;
using linux_analysis_sql_crud::INSERT_APACHE_VHOST;
using linux_analysis_sql_crud::INSERT_NGINX_ACCESS_LOG;
using linux_analysis_sql_crud::INSERT_NGINX_SERVER_BLOCK;

// Security INSERT statements
using linux_analysis_sql_crud::INSERT_SETUID_FILE;
using linux_analysis_sql_crud::INSERT_FILE_CAPABILITY;
using linux_analysis_sql_crud::INSERT_SELINUX_STATUS;
using linux_analysis_sql_crud::INSERT_SELINUX_AVC_DENIAL;
using linux_analysis_sql_crud::INSERT_APPARMOR_PROFILE;
using linux_analysis_sql_crud::INSERT_APPARMOR_VIOLATION;

// Enhanced analysis INSERT statements
using linux_analysis_sql_crud::INSERT_CORRELATED_EVENT;
using linux_analysis_sql_crud::INSERT_ATTACK_CHAIN;
using linux_analysis_sql_crud::INSERT_TIMELINE_EVENT;
using linux_analysis_sql_crud::INSERT_TIMELINE_GAP;
using linux_analysis_sql_crud::INSERT_ANOMALY;

// Base SELECT statements
using linux_analysis_sql_crud::SELECT_LOG_ENTRIES_BASE;
using linux_analysis_sql_crud::SELECT_USERS_BASE;
using linux_analysis_sql_crud::SELECT_GROUPS_BASE;
using linux_analysis_sql_crud::SELECT_LOGIN_RECORDS_BASE;
using linux_analysis_sql_crud::SELECT_SHELL_HISTORY_BASE;
using linux_analysis_sql_crud::SELECT_CRON_JOBS_BASE;
using linux_analysis_sql_crud::SELECT_SSH_KEYS_BASE;
using linux_analysis_sql_crud::SELECT_SSH_KNOWN_HOSTS_BASE;
using linux_analysis_sql_crud::SELECT_PACKAGES_BASE;
using linux_analysis_sql_crud::SELECT_NETWORK_CONNECTIONS_BASE;
using linux_analysis_sql_crud::SELECT_SYSTEMD_SERVICES_BASE;
using linux_analysis_sql_crud::SELECT_KERNEL_MODULES_BASE;
using linux_analysis_sql_crud::SELECT_FIREWALL_RULES_BASE;
using linux_analysis_sql_crud::SELECT_AUDIT_LOGS_BASE;
using linux_analysis_sql_crud::SELECT_BROWSER_PROFILES_BASE;

// Container SELECT statements
using linux_analysis_sql_crud::SELECT_DOCKER_CONTAINERS_BASE;
using linux_analysis_sql_crud::SELECT_DOCKER_IMAGES_BASE;
using linux_analysis_sql_crud::SELECT_DOCKER_VOLUMES_BASE;
using linux_analysis_sql_crud::SELECT_PODMAN_CONTAINERS_BASE;
using linux_analysis_sql_crud::SELECT_PODMAN_PODS_BASE;

// Web server SELECT statements
using linux_analysis_sql_crud::SELECT_APACHE_ACCESS_LOGS_BASE;
using linux_analysis_sql_crud::SELECT_APACHE_VHOSTS_BASE;
using linux_analysis_sql_crud::SELECT_NGINX_ACCESS_LOGS_BASE;
using linux_analysis_sql_crud::SELECT_NGINX_SERVER_BLOCKS_BASE;

// Security SELECT statements
using linux_analysis_sql_crud::SELECT_SETUID_FILES_BASE;
using linux_analysis_sql_crud::SELECT_CAPABILITIES_BASE;
using linux_analysis_sql_crud::SELECT_SELINUX_STATUS_BASE;
using linux_analysis_sql_crud::SELECT_SELINUX_AVC_DENIALS_BASE;
using linux_analysis_sql_crud::SELECT_APPARMOR_PROFILES_BASE;
using linux_analysis_sql_crud::SELECT_APPARMOR_VIOLATIONS_BASE;

// Enhanced analysis SELECT statements
using linux_analysis_sql_crud::SELECT_CORRELATED_EVENTS_BASE;
using linux_analysis_sql_crud::SELECT_ATTACK_CHAINS_BASE;
using linux_analysis_sql_crud::SELECT_TIMELINE_EVENTS_BASE;
using linux_analysis_sql_crud::SELECT_TIMELINE_GAPS_BASE;
using linux_analysis_sql_crud::SELECT_ANOMALIES_BASE;

using linux_analysis_sql_llm::UPDATE_LOG_ENTRY_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_USER_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_LOGIN_RECORD_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_SHELL_HISTORY_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_CRON_JOB_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_SSH_KEY_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_SSH_KNOWN_HOST_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_PACKAGE_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_NETWORK_CONNECTION_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_SYSTEMD_SERVICE_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_KERNEL_MODULE_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_FIREWALL_RULE_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_AUDIT_LOG_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_BROWSER_PROFILE_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_AUDIT_EVENT_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_TAMPERING_FINDING_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_PERSISTENCE_ENTRY_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_JOURNAL_ENTRY_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_WEB_ERROR_LOG_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_MIDDLEWARE_LOG_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_CONTAINER_LOG_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_CONTAINER_SECURITY_FINDING_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_PACKAGE_LOG_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_SUSPICIOUS_PACKAGE_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_ACCOUNT_SECURITY_FINDING_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_SSH_SECURITY_FINDING_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_DATABASE_LOG_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_DATABASE_SECURITY_FINDING_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_EMAIL_LOG_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_EMAIL_SECURITY_FINDING_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_VPN_LOG_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_VPN_SECURITY_FINDING_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_FIREWALL_LOG_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_SECURITY_PRODUCT_LOG_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_SECURITY_PRODUCT_FINDING_LLM_ANALYSIS;
using linux_analysis_sql_llm::UPDATE_MODSECURITY_LOG_LLM_ANALYSIS;

using linux_analysis_sql_llm::SELECT_LOG_ENTRIES_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_USERS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_LOGIN_RECORDS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_SHELL_HISTORY_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_CRON_JOBS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_SSH_KEYS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_SSH_KNOWN_HOSTS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_PACKAGES_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_NETWORK_CONNECTIONS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_SYSTEMD_SERVICES_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_KERNEL_MODULES_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_FIREWALL_RULES_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_AUDIT_LOGS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_BROWSER_PROFILES_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_AUDIT_EVENTS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_TAMPERING_FINDINGS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_PERSISTENCE_ENTRIES_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_JOURNAL_ENTRIES_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_WEB_ERROR_LOGS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_MIDDLEWARE_LOGS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_CONTAINER_LOGS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_CONTAINER_SECURITY_FINDINGS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_PACKAGE_LOGS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_SUSPICIOUS_PACKAGES_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_ACCOUNT_SECURITY_FINDINGS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_SSH_SECURITY_FINDINGS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_DATABASE_LOGS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_DATABASE_SECURITY_FINDINGS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_EMAIL_LOGS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_EMAIL_SECURITY_FINDINGS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_VPN_LOGS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_VPN_SECURITY_FINDINGS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_FIREWALL_LOGS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_SECURITY_PRODUCT_LOGS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_SECURITY_PRODUCT_FINDINGS_PENDING_ANALYSIS;
using linux_analysis_sql_llm::SELECT_MODSECURITY_LOGS_PENDING_ANALYSIS;

using linux_analysis_sql_llm::INSERT_LINUX_ANALYSIS_PROGRESS;
using linux_analysis_sql_llm::UPDATE_LINUX_ANALYSIS_PROGRESS;
using linux_analysis_sql_llm::COMPLETE_LINUX_ANALYSIS_PROGRESS;

} // namespace LinuxAnalysisSQL

#endif // LINUX_ANALYSIS_SQL_H
