// windows_analysis_sql.h
// SQL statements for Windows forensic analysis database - Main declarations

#pragma once
#ifndef WINDOWS_ANALYSIS_SQL_H
#define WINDOWS_ANALYSIS_SQL_H

// Include modular SQL components
#include "DatabaseManager/SQL/windows_analysis_sql_tables.h"
#include "DatabaseManager/SQL/windows_analysis_sql_crud.h"
#include "DatabaseManager/SQL/windows_analysis_sql_llm.h"

namespace WindowsAnalysisSQL {

// Re-export all symbols for backward compatibility
using windows_analysis_sql_tables::CREATE_ALL_TABLES;
using windows_analysis_sql_tables::CREATE_WINDOWS_ANALYSIS_PROGRESS_TABLE;

using windows_analysis_sql_crud::INSERT_REGISTRY_VALUE;
using windows_analysis_sql_crud::INSERT_EVENT_LOG;
using windows_analysis_sql_crud::INSERT_PREFETCH_FILE;
using windows_analysis_sql_crud::INSERT_LNK_FILE;
using windows_analysis_sql_crud::INSERT_JUMP_LIST_ENTRY;
using windows_analysis_sql_crud::INSERT_USER_ACCOUNT;
using windows_analysis_sql_crud::INSERT_USB_DEVICE;
using windows_analysis_sql_crud::INSERT_RECYCLE_BIN_ENTRY;
using windows_analysis_sql_crud::INSERT_BROWSER_ARTIFACT;
using windows_analysis_sql_crud::INSERT_MFT_ENTRY;
using windows_analysis_sql_crud::INSERT_WINDOWS_SERVICE;
using windows_analysis_sql_crud::INSERT_SCHEDULED_TASK;
using windows_analysis_sql_crud::INSERT_AMCACHE_ENTRY;
using windows_analysis_sql_crud::INSERT_SRUM_ENTRY;
using windows_analysis_sql_crud::INSERT_BROWSER_HISTORY;
using windows_analysis_sql_crud::INSERT_BROWSER_DOWNLOAD;
using windows_analysis_sql_crud::INSERT_BROWSER_BOOKMARK;
using windows_analysis_sql_crud::INSERT_BROWSER_COOKIE;
using windows_analysis_sql_crud::INSERT_BROWSER_LOGIN;

using windows_analysis_sql_crud::SELECT_REGISTRY_VALUES_BASE;
using windows_analysis_sql_crud::SELECT_EVENT_LOGS_BASE;
using windows_analysis_sql_crud::SELECT_PREFETCH_FILES_BASE;
using windows_analysis_sql_crud::SELECT_LNK_FILES_BASE;
using windows_analysis_sql_crud::SELECT_JUMP_LIST_ENTRIES_BASE;
using windows_analysis_sql_crud::SELECT_USER_ACCOUNTS_BASE;
using windows_analysis_sql_crud::SELECT_USB_DEVICES_BASE;
using windows_analysis_sql_crud::SELECT_RECYCLE_BIN_BASE;
using windows_analysis_sql_crud::SELECT_BROWSER_ARTIFACTS_BASE;
using windows_analysis_sql_crud::SELECT_MFT_ENTRIES_BASE;
using windows_analysis_sql_crud::SELECT_WINDOWS_SERVICES_BASE;
using windows_analysis_sql_crud::SELECT_SCHEDULED_TASKS_BASE;
using windows_analysis_sql_crud::SELECT_AMCACHE_ENTRIES_BASE;
using windows_analysis_sql_crud::SELECT_SRUM_ENTRIES_BASE;
using windows_analysis_sql_crud::SELECT_BROWSER_HISTORY_BASE;
using windows_analysis_sql_crud::SELECT_BROWSER_DOWNLOADS_BASE;
using windows_analysis_sql_crud::SELECT_BROWSER_BOOKMARKS_BASE;
using windows_analysis_sql_crud::SELECT_BROWSER_COOKIES_BASE;
using windows_analysis_sql_crud::SELECT_BROWSER_LOGINS_BASE;

using windows_analysis_sql_llm::UPDATE_REGISTRY_LLM_ANALYSIS;
using windows_analysis_sql_llm::UPDATE_EVENT_LOG_LLM_ANALYSIS;
using windows_analysis_sql_llm::UPDATE_PREFETCH_LLM_ANALYSIS;
using windows_analysis_sql_llm::UPDATE_LNK_LLM_ANALYSIS;
using windows_analysis_sql_llm::UPDATE_JUMP_LIST_LLM_ANALYSIS;
using windows_analysis_sql_llm::UPDATE_BROWSER_HISTORY_LLM_ANALYSIS;
using windows_analysis_sql_llm::UPDATE_BROWSER_DOWNLOAD_LLM_ANALYSIS;
using windows_analysis_sql_llm::UPDATE_BROWSER_BOOKMARK_LLM_ANALYSIS;
using windows_analysis_sql_llm::UPDATE_BROWSER_LOGIN_LLM_ANALYSIS;
using windows_analysis_sql_llm::UPDATE_MFT_LLM_ANALYSIS;
using windows_analysis_sql_llm::UPDATE_WINDOWS_SERVICE_LLM_ANALYSIS;
using windows_analysis_sql_llm::UPDATE_SCHEDULED_TASK_LLM_ANALYSIS;
using windows_analysis_sql_llm::UPDATE_AMCACHE_LLM_ANALYSIS;
using windows_analysis_sql_llm::UPDATE_SRUM_LLM_ANALYSIS;

using windows_analysis_sql_llm::SELECT_REGISTRY_PENDING_ANALYSIS;
using windows_analysis_sql_llm::SELECT_EVENT_LOGS_PENDING_ANALYSIS;
using windows_analysis_sql_llm::SELECT_PREFETCH_PENDING_ANALYSIS;
using windows_analysis_sql_llm::SELECT_LNK_PENDING_ANALYSIS;
using windows_analysis_sql_llm::SELECT_JUMP_LIST_PENDING_ANALYSIS;
using windows_analysis_sql_llm::SELECT_BROWSER_HISTORY_PENDING_ANALYSIS;
using windows_analysis_sql_llm::SELECT_BROWSER_DOWNLOAD_PENDING_ANALYSIS;
using windows_analysis_sql_llm::SELECT_BROWSER_BOOKMARK_PENDING_ANALYSIS;
using windows_analysis_sql_llm::SELECT_BROWSER_LOGIN_PENDING_ANALYSIS;
using windows_analysis_sql_llm::SELECT_MFT_PENDING_ANALYSIS;
using windows_analysis_sql_llm::SELECT_WINDOWS_SERVICE_PENDING_ANALYSIS;
using windows_analysis_sql_llm::SELECT_SCHEDULED_TASK_PENDING_ANALYSIS;
using windows_analysis_sql_llm::SELECT_AMCACHE_PENDING_ANALYSIS;
using windows_analysis_sql_llm::SELECT_SRUM_PENDING_ANALYSIS;

using windows_analysis_sql_llm::INSERT_WINDOWS_ANALYSIS_PROGRESS;
using windows_analysis_sql_llm::UPDATE_WINDOWS_ANALYSIS_PROGRESS;
using windows_analysis_sql_llm::COMPLETE_WINDOWS_ANALYSIS_PROGRESS;

} // namespace WindowsAnalysisSQL

#endif // WINDOWS_ANALYSIS_SQL_H
