# CMake generated Testfile for 
# Source directory: /home/ymj68520/projects/Forensics/ForensicsProject/tests
# Build directory: /home/ymj68520/projects/Forensics/ForensicsProject/web/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(LinuxAnalyzerGTests "/home/ymj68520/projects/Forensics/ForensicsProject/web/tests/test_linux_analyzer_gtest")
set_tests_properties(LinuxAnalyzerGTests PROPERTIES  _BACKTRACE_TRIPLES "/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;56;add_test;/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;0;")
add_test(FileClassifierTests "/home/ymj68520/projects/Forensics/ForensicsProject/web/tests/test_file_classifier")
set_tests_properties(FileClassifierTests PROPERTIES  _BACKTRACE_TRIPLES "/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;70;add_test;/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;0;")
add_test(AuditLogGTests "/home/ymj68520/projects/Forensics/ForensicsProject/web/tests/test_audit_log_gtest")
set_tests_properties(AuditLogGTests PROPERTIES  _BACKTRACE_TRIPLES "/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;80;add_test;/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;0;")
add_test(FileCarvingTests "/home/ymj68520/projects/Forensics/ForensicsProject/web/tests/test_file_carving")
set_tests_properties(FileCarvingTests PROPERTIES  _BACKTRACE_TRIPLES "/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;89;add_test;/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;0;")
add_test(WindowsParsersGTests "/home/ymj68520/projects/Forensics/ForensicsProject/web/tests/test_windows_parsers_gtest")
set_tests_properties(WindowsParsersGTests PROPERTIES  _BACKTRACE_TRIPLES "/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;105;add_test;/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;0;")
add_test(AndroidAnalyzerGTests "/home/ymj68520/projects/Forensics/ForensicsProject/web/tests/test_android_analyzer_gtest")
set_tests_properties(AndroidAnalyzerGTests PROPERTIES  _BACKTRACE_TRIPLES "/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;114;add_test;/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;0;")
add_test(FullTextSearchGTests "/home/ymj68520/projects/Forensics/ForensicsProject/web/tests/test_fulltext_search_gtest")
set_tests_properties(FullTextSearchGTests PROPERTIES  _BACKTRACE_TRIPLES "/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;126;add_test;/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;0;")
add_test(ImageAnalyzerGTests "/home/ymj68520/projects/Forensics/ForensicsProject/web/tests/test_image_analyzer_gtest")
set_tests_properties(ImageAnalyzerGTests PROPERTIES  _BACKTRACE_TRIPLES "/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;134;add_test;/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;0;")
add_test(LLMIntegrationGTests "/home/ymj68520/projects/Forensics/ForensicsProject/web/tests/test_llm_integration")
set_tests_properties(LLMIntegrationGTests PROPERTIES  _BACKTRACE_TRIPLES "/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;172;add_test;/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;0;")
add_test(PDFAnalyzerTests "/home/ymj68520/projects/Forensics/ForensicsProject/web/tests/test_pdf_analyzer")
set_tests_properties(PDFAnalyzerTests PROPERTIES  _BACKTRACE_TRIPLES "/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;185;add_test;/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;0;")
add_test(OfficeAnalyzerTests "/home/ymj68520/projects/Forensics/ForensicsProject/web/tests/test_office_analyzer")
set_tests_properties(OfficeAnalyzerTests PROPERTIES  _BACKTRACE_TRIPLES "/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;198;add_test;/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;0;")
add_test(ConfigManagerTests "/home/ymj68520/projects/Forensics/ForensicsProject/web/tests/test_config_manager")
set_tests_properties(ConfigManagerTests PROPERTIES  _BACKTRACE_TRIPLES "/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;267;add_test;/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;0;")
add_test(ThreadPoolTests "/home/ymj68520/projects/Forensics/ForensicsProject/web/tests/test_thread_pool")
set_tests_properties(ThreadPoolTests PROPERTIES  _BACKTRACE_TRIPLES "/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;282;add_test;/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;0;")
add_test(LoggerTests "/home/ymj68520/projects/Forensics/ForensicsProject/web/tests/test_logger")
set_tests_properties(LoggerTests PROPERTIES  _BACKTRACE_TRIPLES "/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;292;add_test;/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;0;")
add_test(ErrorHandlingTests "/home/ymj68520/projects/Forensics/ForensicsProject/web/tests/test_error_handling")
set_tests_properties(ErrorHandlingTests PROPERTIES  _BACKTRACE_TRIPLES "/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;302;add_test;/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;0;")
add_test(TOONExporterTests "/home/ymj68520/projects/Forensics/ForensicsProject/web/tests/test_toon_exporter")
set_tests_properties(TOONExporterTests PROPERTIES  _BACKTRACE_TRIPLES "/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;315;add_test;/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;0;")
add_test(OSSAnalyzerGTests "/home/ymj68520/projects/Forensics/ForensicsProject/web/tests/test_oss_analyzer_gtest")
set_tests_properties(OSSAnalyzerGTests PROPERTIES  _BACKTRACE_TRIPLES "/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;335;add_test;/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;0;")
add_test(DatabaseAnalyzerGTests "/home/ymj68520/projects/Forensics/ForensicsProject/web/tests/test_database_analyzer_gtest")
set_tests_properties(DatabaseAnalyzerGTests PROPERTIES  _BACKTRACE_TRIPLES "/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;361;add_test;/home/ymj68520/projects/Forensics/ForensicsProject/tests/CMakeLists.txt;0;")
