"""DLL Markdown report generator."""

from typing import Dict, Any, List


class DLLMarkdownGenerator:
    """Generate Markdown reports from DLL analysis results."""

    def __init__(self):
        """Initialize the markdown generator."""
        pass

    def generate_report(self, analysis_result: Dict[str, Any]) -> str:
        """
        Generate a Markdown report from analysis results.

        Args:
            analysis_result: Analysis result from DLLAnalyzerClient

        Returns:
            Markdown formatted string
        """
        lines = []

        # Header
        file_name = analysis_result.get("file_name", "Unknown")
        lines.append(f"# DLL Analysis Report: {file_name}")
        lines.append("")

        # Basic Info
        lines.append("## File Information")
        lines.append(f"- **Format**: {analysis_result.get('format', 'Unknown')}")
        lines.append(f"- **Size**: {analysis_result.get('file_size', 0)} bytes")
        lines.append(f"- **MD5**: `{analysis_result.get('md5', 'N/A')}`")
        lines.append(f"- **SHA256**: `{analysis_result.get('sha256', 'N/A')}`")
        lines.append(f"- **Signature Status**: {analysis_result.get('signature_status', 'Unknown')}")
        lines.append("")

        # Threat Score
        threat_score = analysis_result.get("threat_score", 0)
        threat_level = self._get_threat_level(threat_score)
        lines.append("## Threat Assessment")
        lines.append(f"- **Score**: {threat_score}/100")
        lines.append(f"- **Level**: {threat_level}")
        lines.append("")

        # Sections
        sections = analysis_result.get("sections", [])
        if sections:
            lines.append("## Sections")
            lines.append("| Name | Virtual Address | Virtual Size | Raw Size |")
            lines.append("|------|----------------|--------------|----------|")
            for section in sections:
                name = section.get("name", "Unknown")
                va = section.get("virtual_address", 0)
                vs = section.get("virtual_size", 0)
                rs = section.get("raw_size", 0)
                lines.append(f"| {name} | {va:#x} | {vs:#x} | {rs:#x} |")
            lines.append("")

        # Imports
        imports = analysis_result.get("imports", [])
        if imports:
            lines.append("## Imported Functions")
            lines.append("| DLL | Function |")
            lines.append("|-----|----------|")
            for imp in imports:
                dll = imp.get("dll", "Unknown")
                func = imp.get("function", "Unknown")
                lines.append(f"| {dll} | {func} |")
            lines.append("")

        # Exports
        exports = analysis_result.get("exports", [])
        if exports:
            lines.append("## Exported Functions")
            lines.append("| Function | Address |")
            lines.append("|----------|---------|")
            for exp in exports:
                name = exp.get("name", "Unknown")
                addr = exp.get("address", 0)
                lines.append(f"| {name} | {addr:#x} |")
            lines.append("")

        # Anomalies
        anomalies = analysis_result.get("anomalies", [])
        if anomalies:
            lines.append("## Anomalies")
            for anomaly in anomalies:
                lines.append(f"- {anomaly}")
            lines.append("")

        lines.append("---")
        lines.append("*Report generated by DLL Analyzer*")

        return "\n".join(lines)

    def _get_threat_level(self, score: int) -> str:
        """Convert threat score to human-readable level."""
        if score >= 80:
            return "CRITICAL"
        elif score >= 60:
            return "HIGH"
        elif score >= 40:
            return "MEDIUM"
        elif score >= 20:
            return "LOW"
        else:
            return "SAFE"
