#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
TESTS_DIR="$ROOT_DIR/tests"
IMAGE="${1:-$TESTS_DIR/android_test.img}"
SYSTEM_ASSETS_DIR="$TESTS_DIR/system_assets"

echo "Creating system directory assets..."

# Create system assets directory
rm -rf "$SYSTEM_ASSETS_DIR"
mkdir -p "$SYSTEM_ASSETS_DIR"

# Create build.prop
cat > "$SYSTEM_ASSETS_DIR/build.prop" <<BUILDPROP
# begin build properties
# autogenerated by buildinfo.sh
ro.build.id=TP1A.220624.014
ro.build.display.id=TP1A.220624.014
ro.build.version.incremental=8650216
ro.build.version.sdk=33
ro.build.version.preview_sdk=0
ro.build.version.codename=REL
ro.build.version.all_codenames=REL
ro.build.version.release=13
ro.build.version.release_or_codename=13
ro.build.version.security_patch=2022-08-05
ro.build.version.base_os=
ro.build.version.min_supported_target_sdk=23
ro.build.date=Wed Aug 10 00:00:00 UTC 2022
ro.build.date.utc=1660089600
ro.build.type=user
ro.build.user=android-build
ro.build.host=abfarm000
ro.build.tags=release-keys
ro.build.flavor=generic_x86_64-user
ro.product.model=Android SDK built for x86_64
ro.product.brand=generic
ro.product.name=generic_x86_64
ro.product.device=generic_x86_64
ro.product.board=
ro.product.cpu.abi=x86_64
ro.product.cpu.abilist=x86_64,x86
ro.product.cpu.abilist32=x86
ro.product.cpu.abilist64=x86_64
ro.product.manufacturer=Google
ro.product.locale=en-US
ro.product.first_api_level=23
ro.board.platform=generic_x86_64
# ro.build.product is obsolete; use ro.product.device
ro.build.product=generic_x86_64
# Do not try to parse description or thumbprint
ro.build.description=generic_x86_64-user 13 TP1A.220624.014 8650216 release-keys
ro.build.fingerprint=generic/generic_x86_64/generic_x86_64:13/TP1A.220624.014/8650216:user/release-keys
ro.build.characteristics=default
# end build properties
BUILDPROP

# Create system app directories and sample APK files
mkdir -p "$SYSTEM_ASSETS_DIR/app"
mkdir -p "$SYSTEM_ASSETS_DIR/priv-app"
mkdir -p "$SYSTEM_ASSETS_DIR/framework"

# Create sample system APK (just a dummy file with APK-like content)
echo "Sample System App APK content" > "$SYSTEM_ASSETS_DIR/SystemUI.apk"
echo "Sample Privileged App APK content" > "$SYSTEM_ASSETS_DIR/Settings.apk"

# Create framework files
echo "Sample framework JAR content" > "$SYSTEM_ASSETS_DIR/framework.jar"
echo "Sample framework DEX content" > "$SYSTEM_ASSETS_DIR/framework.dex"
echo "Sample framework SO content" > "$SYSTEM_ASSETS_DIR/framework.so"

echo "System assets created in $SYSTEM_ASSETS_DIR"

# Use debugfs to add system directory to the image
if command -v debugfs >/dev/null 2>&1; then
    echo "Adding system directory to $IMAGE using debugfs..."

    debugfs -w "$IMAGE" <<EOF
mkdir /system
mkdir /system/app
mkdir /system/priv-app
mkdir /system/framework

write "$SYSTEM_ASSETS_DIR/build.prop" /system/build.prop
write "$SYSTEM_ASSETS_DIR/SystemUI.apk" /system/app/SystemUI.apk
write "$SYSTEM_ASSETS_DIR/Settings.apk" /system/priv-app/Settings.apk
write "$SYSTEM_ASSETS_DIR/framework.jar" /system/framework/framework.jar
write "$SYSTEM_ASSETS_DIR/framework.dex" /system/framework/framework.dex
write "$SYSTEM_ASSETS_DIR/framework.so" /system/framework/framework.so

quit
EOF

    echo "System directory added to $IMAGE"
else
    echo "debugfs not found. Cannot add system directory to image."
    echo "Please install e2fsprogs package."
    exit 1
fi

# Clean up
rm -rf "$SYSTEM_ASSETS_DIR"

echo "System directory creation complete!"
