"""Shared protocol models and identifiers for forensic reports."""

from .ids import safe_segment, stable_record_id
from .models import (
    AdapterContext,
    AdapterWarning,
    AnalysisReference,
    CategoryIndex,
    CategorySpec,
    DataState,
    EnvelopeBoundAnalysisReviewV1,
    EnvelopeBoundAnalysisV1,
    EnvelopeClaimV1,
    EnvelopeEvidenceItemV1,
    EnvelopeSnapshotV1,
    EvidenceSource,
    PageShard,
    ProbeResult,
    ReportAdapter,
    ReportAttachment,
    ReportGenerationEnvelopeV1,
    ReportGenerationInput,
    ReportManifest,
    ReportRecord,
    ReportStatus,
    ReportVersion,
    ScopeType,
    SearchHit,
    Severity,
    SourceFingerprint,
)

__all__ = [
    "AdapterContext",
    "AdapterWarning",
    "AnalysisReference",
    "CategoryIndex",
    "CategorySpec",
    "DataState",
    "EnvelopeBoundAnalysisReviewV1",
    "EnvelopeBoundAnalysisV1",
    "EnvelopeClaimV1",
    "EnvelopeEvidenceItemV1",
    "EnvelopeSnapshotV1",
    "EvidenceSource",
    "PageShard",
    "ProbeResult",
    "ReportAdapter",
    "ReportAttachment",
    "ReportGenerationEnvelopeV1",
    "ReportGenerationInput",
    "ReportManifest",
    "ReportRecord",
    "ReportStatus",
    "ReportVersion",
    "ScopeType",
    "SearchHit",
    "Severity",
    "SourceFingerprint",
    "safe_segment",
    "stable_record_id",
]
